base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getRoutes),
    path('rooms/<str:pk>', views.getRoom),
    path('rooms/', views.getRooms),
]

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('register/', views.registerUser, name='register'),

    path('', views.index, name='index'),
    path('rooms/<str:pk>/destroy/', views.destroyRoom, name='rooms.destroy'),
    path('rooms/<str:pk>/update/', views.updateRoom, name='rooms.update'),
    path('rooms/create/', views.createRoom, name='rooms.create'),
    path('rooms/<str:pk>', views.room, name='rooms.show'),
    path('profile/update/', views.updateProfile, name='profile.update'),
    path('profile/<str:pk>/', views.profile, name='profile.show'),
    path('messages/<str:pk>/destroy', views.destroyMessage, name='messages.destroy'),
    path('topics/', views.topics, name='topics.index'),
    path('activities/', views.activities, name='activities.index'),
]

django_study_buddy_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('base.urls')),

    path('api/', include('base.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True)

    avatar = models.ImageField(null=True, default="avatar.svg")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(to=User, related_name='participants', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at', '-created_at']

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at', '-created_at']

    def __str__(self):
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Room, User


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'avatar', 'bio']

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer


@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id',
    ]
    return Response(routes)


@api_view(['GET'])
def getRooms(requests):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getRoom(requests, pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

base/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.db.models import Q
from .models import Room, Topic, Message, User
from .forms import RoomForm, UserForm, MyUserCreationForm


# rooms = [
#     {"id": 1, "name": "Let's learn Python!"},
#     {"id": 2, "name": "Design with me"},
#     {"id": 3, "name": "Frontend developers"},
# ]

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('index')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')
        try:
            User.objects.get(email=email)
        except:
            messages.error(request, 'User does not exists.')

        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.error(request, 'Username or password does not exists')

    context = {}
    return render(request, 'base/auth/login.html', context=context)


def logoutPage(request):
    logout(request)
    return redirect('index')


def registerUser(request):
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.email = user.email.lower()  # 用户名转换为小写
            user.save()
            login(request, user)
            return redirect('index')
        else:
            messages.error(request, 'An error occurred during register')

    form = MyUserCreationForm()
    context = {'form': form}
    return render(request, 'base/auth/register.html', context=context)


def index(request):
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__contains=q) |
        Q(description__contains=q)
    )
    topics = Topic.objects.all()[:5]  # 获取前5条数据
    room_count = rooms.count()
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))

    context = {'rooms': rooms, 'topics': topics, 'room_count': room_count, 'room_messages': room_messages}
    return render(request, 'base/index.html', context=context)


def room(request, pk):
    room = Room.objects.get(id=pk)
    room_messages = room.message_set.all().order_by('-created_at')
    participants = room.participants.all()
    if request.method == 'POST':
        message = Message.objects.create(user=request.user, room=room, body=request.POST.get('body'))
        room.participants.add(request.user)
        return redirect('rooms.show', pk=room.id)

    context = {"room": room, 'room_messages': room_messages, 'participants': participants}
    return render(request, 'base/rooms/show.html', context=context)


@login_required(login_url='/login')
def profile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.room_set.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()

    context = {'user': user, 'rooms': rooms, 'room_messages': room_messages, 'topics': topics}
    return render(request, 'base/auth/profile/show.html', context=context)


@login_required(login_url='/login')
def createRoom(request):
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description')
        )

        return redirect('index')

    form = RoomForm()
    topics = Topic.objects.all()
    context = {'form': form, 'topics': topics}
    return render(request, 'base/rooms/form.html', context=context)


@login_required(login_url='/login')
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)

    if request.user != room.host:
        return HttpResponse('Your are not allowed here')

    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get('name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.save()
        return redirect('index')

    topics = Topic.objects.all()
    context = {"form": form, 'topics': topics, 'room': room}
    return render(request, 'base/rooms/form.html', context=context)


@login_required(login_url='/login')
def destroyRoom(request, pk):
    room = Room.objects.get(id=pk)

    if request.method == 'POST':
        room.delete()
        return redirect('index')

    context = {"obj": room}
    return render(request, 'base/destroy.html', context=context)


@login_required(login_url='/login')
def destroyMessage(request, pk):
    message = Message.objects.get(id=pk)

    if request.user != message.user:
        return HttpResponse('You are not allowed here')

    if request.method == 'POST':
        message.delete()
        return redirect('rooms.show', message.room.id)

    context = {"obj": message}
    return render(request, 'base/destroy.html', context=context)


@login_required(login_url='/login')
def updateProfile(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()  # 用户名转换为小写
            user.save()
            return redirect('profile.show', user.id)

    context = {'form': form}
    return render(request, 'base/auth/profile/update.html', context=context)


def topics(request):
    q = request.GET.get('q') if request.GET.get('q') is not None else ''

    topics = Topic.objects.filter(name__contains=q)

    context = {'topics': topics}
    return render(request, 'base/topics/index.html', context=context)


def activities(request):
    room_messages = Message.objects.all()
    context = {'room_messages': room_messages}

    return render(request, 'base/activities/index.html', context=context)

base/templates/base/activities.html
{% extends 'main.html' %}
{% block content %}
    <main class="layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                                ></path>
                            </svg>
                        </a>
                        <h3>Recent Activities</h3>
                    </div>
                </div>

                <div class="activities-page layout__body">

                    {% for room_message in room_messages %}
                        <div class="activities__box">
                            <div class="activities__boxHeader roomListRoom__header">
                                <a href="{% url 'profile.show' room_message.user.id %}" class="roomListRoom__author">
                                    <div class="avatar avatar--small">
                                        <img src="{{ room_message.user.avatar.url }}" alt=""/>
                                    </div>
                                    <p>
                                        @{{ room_message.user.username }}
                                        <span>{{ room_message.created_at|timesince }} ago</span>
                                    </p>
                                </a>
                                {% if room_message.user.id is request.user.id %}
                                    <div class="roomListRoom__actions">
                                        <a href="{% url 'messages.destroy' room_message.id %}">
                                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                                 viewBox="0 0 32 32">
                                                <title>remove</title>
                                                <path
                                                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                                                ></path>
                                            </svg>
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="activities__boxContent">
                                <p>replied to post “<a href="">{{ room_message.room.name }}</a>”</p>
                                <div class="activities__boxRoomContent">
                                    {{ room_message }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

base/templates/base/destroy.html
{% extends 'layouts/main.html' %}
{% block content %}
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{ request.META.HTTP_REFERER }}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="POST">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{ obj }}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm"/>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

base/templates/base/home.html
{% extends 'main.html' %}
{% block content %}
    <main class="layout layout--3">
        <div class="container">
            <!-- Topics Start -->
            {% include 'base/components/topics.html' %}
            <!-- Topics End -->

            <!-- Room List Start -->
            <div class="roomList">
                <div class="mobile-menu">
                    <form action="{% url 'home' %}" method="GET" class="header__search">
                        <label>
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>search</title>
                                <path
                                        d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                                ></path>
                            </svg>
                            <input name="q" placeholder="Search for posts"/>
                        </label>
                    </form>
                    <div class="mobile-menuItems">
                        <a class="btn btn--main btn--pill" href="{% url 'topics.index' %}">Browse Topics</a>
                        <a class="btn btn--main btn--pill" href="{% url 'activities.index' %}">Recent Activities</a>
                    </div>
                </div>
                <div class="roomList__header">
                    <div>
                        <h2>Study Room</h2>
                        <p>{{ rooms.count }} Rooms available</p>
                    </div>
                    <a class="btn btn--main" href="{% url 'rooms.create' %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                             viewBox="0 0 32 32">
                            <title>add</title>
                            <path
                                    d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                            ></path>
                        </svg>
                        Create Room
                    </a>
                </div>

                {% include 'base/components/feeds.html' %}
            </div>
            <!-- Room List End -->

            <!-- Activities Start -->
            {% include 'base/components/activities.html' %}
            <!-- Activities End -->
        </div>
    </main>
{% endblock %}

base/templates/base/index.html
{% extends 'layouts/main.html' %}
{% block content %}
    <main class="layout layout--3">
        <div class="container">
            <!-- Topics Start -->
            {% include 'base/components/topics.html' %}
            <!-- Topics End -->

            <!-- Room List Start -->
            <div class="roomList">
                <div class="mobile-menu">
                    <form action="{% url 'index' %}" method="GET" class="header__search">
                        <label>
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>search</title>
                                <path
                                        d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                                ></path>
                            </svg>
                            <input name="q" placeholder="Search for posts"/>
                        </label>
                    </form>
                    <div class="mobile-menuItems">
                        <a class="btn btn--main btn--pill" href="{% url 'topics.index' %}">Browse Topics</a>
                        <a class="btn btn--main btn--pill" href="{% url 'activities.index' %}">Recent Activities</a>
                    </div>
                </div>
                <div class="roomList__header">
                    <div>
                        <h2>Study Room</h2>
                        <p>{{ rooms.count }} Rooms available</p>
                    </div>
                    <a class="btn btn--main" href="{% url 'rooms.create' %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                             viewBox="0 0 32 32">
                            <title>add</title>
                            <path
                                    d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                            ></path>
                        </svg>
                        Create Room
                    </a>
                </div>

                {% include 'base/components/feeds.html' %}
            </div>
            <!-- Room List End -->

            <!-- Activities Start -->
            {% include 'base/components/activities.html' %}
            <!-- Activities End -->
        </div>
    </main>
{% endblock %}

base/templates/base/login.html
{% extends 'main.html' %}

{% block content %}
    <main class="auth layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <h3>Login</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <h2 class="auth__tagline">Find your study partner</h2>

                    <form class="form" action="" method="POST">
                        {% csrf_token %}
                        <div class="form__group">
                            <label for="id_email">Email</label>
                            <input id="id_email" name="email" type="text" placeholder="e.g. curder@gmail.com" />
                        </div>
                        <div class="form__group">
                            <label for="password">Password</label>
                            <input id="password" name="password" type="password"
                                   placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"/>
                        </div>

                        <button class="btn btn--main" type="submit">
                            <svg
                                    version="1.1"
                                    xmlns="http://www.w3.org/2000/svg"
                                    width="32"
                                    height="32"
                                    viewBox="0 0 32 32"
                            >
                                <title>lock</title>
                                <path
                                        d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                                ></path>
                                <path
                                        d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                                ></path>
                            </svg>

                            Login
                        </button>
                    </form>

                    <div class="auth__action">
                        <p>Haven't signed up yet?</p>
                        <a href="{% url 'register' %}" class="btn btn--link">Sign Up</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

base/templates/base/profile.html
{% extends 'main.html' %}

{% block content %}
    <main class="profile-page layout layout--3">
        <div class="container">
            <div>
                {% include 'base/components/topics.html' %}
            </div>
            <div>
                <div class="profile">
                    <div class="profile__avatar">
                        <div class="avatar avatar--large active">
                            <img src="{{ user.avatar.url }}"/>
                        </div>
                    </div>
                    <div class="profile__info">
                        <h3>{{ user.username }}</h3>
                        <p>@{{ user.username }}</p>
                        {% if request.user == user %}
                            <a href="{% url 'profile.update' %}" class="btn btn--main btn--pill">Edit Profile</a>
                        {% endif %}
                    </div>
                    <div class="profile__about">
                        <h3>About</h3>
                        <p>{{ user.bio }}</p>
                    </div>
                </div>
                <div class="roomList__header">
                    <div>
                        <h2>Study Rooms Hosted by {{ user.username }}</h2>
                    </div>
                </div>
                {% include 'base/components/feeds.html' %}
            </div>
            <div>
                {% include 'base/components/activities.html' %}
            </div>
        </div>
    </main>
{% endblock %}

base/templates/base/register.html
{% extends 'main.html' %}

{% block content %}
    <main class="auth layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <h3>Sign up</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <h2 class="auth__tagline">Find your study partner</h2>

                    <form class="form" action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form__group form__group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                <input id="{{ field.id_for_label }}" name="{{ field.name }}"
                                       type="{{ field.widget_type }}"/>
                            </div>
                        {% endfor %}

                        <button class="btn btn--main" type="submit">
                            <svg
                                    version="1.1"
                                    xmlns="http://www.w3.org/2000/svg"
                                    width="32"
                                    height="32"
                                    viewBox="0 0 32 32"
                            >
                                <title>lock</title>
                                <path
                                        d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                                ></path>
                                <path
                                        d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                                ></path>
                            </svg>

                            Sign Up
                        </button>
                    </form>

                    <div class="auth__action">
                        <p>Already have an account?</p>
                        <a href="{% url 'login' %}" class="btn btn--link">Log In</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

base/templates/base/room_form.html
{% extends 'main.html' %}

{% block content %}
    <main class="create-room layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Create/Update Study Room</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="POST">
                        {% csrf_token %}

                        <div class="form__group">
                            <label for="id_room_topic">Enter a Topic</label>
                            <input required type="text" value="{{ room.topic.name }}" name="topic" list="topic-list"/>
                            <datalist id="topic-list">
                                <select id="id_room_topic">
                                    {% for topic in topics %}
                                        <option value="{{ topic.name }}">{{ topic.name }}</option>
                                    {% endfor %}
                                </select>
                            </datalist>
                        </div>

                        <div class="form__group">
                            <label for="id_name">Room Name</label>
                            {{ form.name }}
                        </div>

                        <div class="form__group">
                            <label for="id_description">Room Description</label>
                            {{ form.description }}
                        </div>

                        <div class="form__action">
                            <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
                            <button class="btn btn--main" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

{#    <div>#}
{#        <form action="" method="POST">#}
{#            {% csrf_token %}#}
{##}
{#            {{ form.as_p }}#}
{##}
{#            <button type="submit">submit</button>#}
{#        </form>#}
{#    </div>#}